[package]
name = "kmerANI"
version = "0.1.0"
edition = "2024"

[dependencies]
async-std = "1.13.2"
clap = { version = "4.5.48", features = ["derive"] }
figlet-rs = "0.1.5"
tokio = { version = "1.47.1", features = ["full"] }
